# Generated by Django 5.2.7 on 2025-10-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imege',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
