# Generated by Django 5.2.7 on 2025-10-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_imege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imege',
            new_name='image',
        ),
    ]
